name: Java Unit CI
on:
  push:
    branches:
    - main
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [
          11.x,
          17.x
        ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
      - name: SDK API Build with Maven
        run: (cd faas-sdk-api/ && mvn install)
      - name: SDK Build and Test with Maven
        run: (cd faas-sdk/ && mvn test)
